#line 2 "elf_lexer.cc"

#line 4 "elf_lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer elf__create_buffer
#define yy_delete_buffer elf__delete_buffer
#define yy_flex_debug elf__flex_debug
#define yy_init_buffer elf__init_buffer
#define yy_flush_buffer elf__flush_buffer
#define yy_load_buffer_state elf__load_buffer_state
#define yy_switch_to_buffer elf__switch_to_buffer
#define yyin elf_in
#define yyleng elf_leng
#define yylex elf_lex
#define yylineno elf_lineno
#define yyout elf_out
#define yyrestart elf_restart
#define yytext elf_text
#define yywrap elf_wrap
#define yyalloc elf_alloc
#define yyrealloc elf_realloc
#define yyfree elf_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE elf_restart(elf_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int elf_leng;

extern FILE *elf_in, *elf_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE elf_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-elf_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < elf_leng; ++yyl )\
                    if ( elf_text[yyl] == '\n' )\
                        --elf_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up elf_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up elf_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via elf_restart()), so that the user can continue scanning by
	 * just pointing elf_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when elf_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int elf_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow elf_wrap()'s to do buffer switches
 * instead of setting up a fresh elf_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void elf_restart (FILE *input_file  );
void elf__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE elf__create_buffer (FILE *file,int size  );
void elf__delete_buffer (YY_BUFFER_STATE b  );
void elf__flush_buffer (YY_BUFFER_STATE b  );
void elf_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void elf_pop_buffer_state (void );

static void elf_ensure_buffer_stack (void );
static void elf__load_buffer_state (void );
static void elf__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER elf__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE elf__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE elf__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE elf__scan_bytes (yyconst char *bytes,int len  );

void *elf_alloc (yy_size_t  );
void *elf_realloc (void *,yy_size_t  );
void elf_free (void *  );

#define yy_new_buffer elf__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        elf_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            elf__create_buffer(elf_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        elf_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            elf__create_buffer(elf_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define elf_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *elf_in = (FILE *) 0, *elf_out = (FILE *) 0;

typedef int yy_state_type;

extern int elf_lineno;

int elf_lineno = 1;

extern char *elf_text;
#define yytext_ptr elf_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up elf_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	elf_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[220] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   19,   17,
        8,   17,   18,   18,   18,   18,   12,   13,   15,   14,
       15,   14,   12,   13,   15,    0,    8,    0,    7,    0,
        0,    9,    0,    7,    0,    0,    0,   12,    0,    0,
       16,   15,   14,    0,   15,   14,   12,   15,   15,   15,
        0,    0,    9,    0,    0,    0,   16,    0,   15,   15,
        0,    0,    0,    0,    0,    0,   15,   15,    0,    0,
        0,    0,    0,    0,    0,    0,   15,   15,   15,    0,
        0,    0,    0,    0,    0,    0,    0,   15,   15,   15,
        0,    0,    0,    0,    0,    0,    0,    0,   15,   15,

       15,    0,    0,    0,    0,    0,    0,    0,    0,   15,
       15,   15,    0,    0,    0,    6,    0,    0,    0,    0,
        0,    0,   15,   15,    0,    0,    2,    0,    0,    0,
        2,    0,   10,    0,   15,   15,    0,    0,    0,    0,
        0,    0,   15,    0,    0,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,    0,    0,    0,   15,   15,
        0,    3,    0,    0,    0,    0,    3,    0,    0,    0,
       15,   15,    0,    1,    0,    0,    0,    1,    0,   11,
       15,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    5,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    7,    8,
        8,    9,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   12,   12,   12,
       13,   13,   13,   13,   13,   13,   14,   13,   13,   13,
       13,   13,   15,   16,   13,   13,   13,   13,   17,   13,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   22,   13,   13,   24,   13,   13,   25,   26,   27,
       28,   13,   13,   29,   30,   31,   13,   32,   13,   33,
       34,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[35] =
    {   0,
        1,    2,    1,    2,    3,    4,    4,    4,    4,    5,
        5,    5,    6,    6,    6,    6,    6,    3,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[255] =
    {   0,
        0,    1,    3,    6,   12,    0,   46,    0,  644,  640,
      695,   78,  695,  635,   79,  605,   81,   84,    0,  104,
      126,  143,   87,  695,  166,  611,  695,  610,  695,   87,
       81,  596,  595,  695,   89,   91,    0,   91,   94,   97,
      113,    0,    0,  114,  195,    0,  118,  135,  139,  152,
      154,  155,  695,  169,  157,    0,  175,  178,  182,  187,
      189,  178,  191,  192,    0,  203,  223,  216,  170,  203,
      208,  212,  218,  219,    0,  226,  232,  248,  253,  226,
      238,  234,  236,  258,  239,    0,  262,  267,  271,  279,
       99,  281,  262,  255,  283,  284,    0,  286,  294,  302,

      311,  288,  298,  305,  296,  307,  313,    0,  316,  327,
      332,  338,  334,  587,  586,  695,  340,  341,  578,  343,
        0,  345,  360,  364,  323,  577,  695,  322,  351,  556,
      695,  352,  695,  367,  371,  381,  356,  353,  367,  374,
      377,  384,  388,  390,  391,  392,  396,  401,  404,  426,
      555,  404,  407,  408,  521,  410,  417,  419,  433,  439,
      520,  695,  519,  411,  428,  515,  695,  514,  421,  447,
      451,  455,  511,  695,  290,  442,  504,  695,  414,  695,
      462,  464,  458,  465,  468,  469,  470,  471,  473,  472,
      474,  478,  475,  476,  477,  479,  480,  235,  482,  484,

      483,  485,  492,  502,  493,  494,  695,  495,  100,  505,
      507,  512,  422,  275,  143,  695,   94,  695,  695,  526,
      532,  538,  544,  550,  555,  559,  564,  570,  573,  577,
      580,  582,  586,  589,  591,  595,  598,  603,  606,  610,
      616,  622,  625,  630,  635,  640,  646,  652,  658,  664,
      670,  676,  682,  688
    } ;

static yyconst flex_int16_t yy_def[255] =
    {   0,
      220,  220,  221,  221,  219,    5,  219,    7,  219,  222,
      219,  223,  219,  219,  224,  219,  225,  219,  226,  226,
      227,  227,  219,  219,  228,  222,  219,  223,  219,  223,
      223,  219,  224,  219,  224,  224,  229,  225,  225,  219,
      219,  226,   20,  230,  227,   22,  219,  228,  228,  228,
      223,  223,  219,  224,  224,  231,  219,  230,  228,  228,
      223,  223,  224,  224,  232,  233,  228,  228,  223,  223,
      223,  224,  224,  224,  234,  233,  228,  228,  228,  223,
      223,  223,  224,  224,  224,  235,  236,  228,  228,  228,
      223,  223,  223,  224,  224,  224,  237,  236,  228,  228,

      228,  223,  223,  238,  224,  224,  224,  239,  240,  228,
      228,  228,  223,  241,  238,  219,  238,  224,  242,  224,
      243,  240,  228,  244,  223,  241,  219,  238,  224,  242,
      219,  224,  219,  245,  228,  244,  223,  238,  238,  224,
      224,  245,  228,  223,  238,  238,  224,  224,  246,  228,
      247,  223,  238,  238,  248,  224,  224,  246,  249,  228,
      247,  219,  250,  238,  238,  248,  219,  251,  224,  219,
      249,  252,  250,  219,  238,  238,  251,  219,  224,  219,
      252,  238,  238,  224,  238,  238,  224,  238,  238,  224,
      238,  238,  224,  238,  238,  224,  238,  238,  224,  238,

      238,  224,  238,  238,  224,  238,  219,  224,  238,  224,
      238,  224,  253,  254,  253,  219,  254,  219,    0,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219
    } ;

static yyconst flex_int16_t yy_nxt[730] =
    {   0,
      219,  219,   11,   11,   12,   12,   14,   15,   16,   14,
       15,   16,   13,   17,   18,   17,   19,   20,   20,   20,
       20,   21,   21,   21,   21,   21,   21,   21,   21,   19,
       22,   22,   22,   22,   22,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   13,   23,   24,   23,
       25,   20,   20,   20,   20,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   20,   20,   20,   20,   20,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       29,   34,   38,   29,   38,   40,   41,   40,   47,   29,
       47,   34,   38,   34,   38,   44,  218,   44,   40,   41,

       40,   29,  116,   52,   30,   35,  211,   31,   36,   43,
       43,   43,   43,   55,   57,   44,   57,   44,   51,   47,
       54,   47,   43,   43,   43,   43,   43,   44,  102,   44,
       42,   42,   42,   42,   42,   33,   33,   34,   33,   33,
       33,   34,   33,   42,   44,  216,   44,   42,   43,   43,
       43,   43,   33,   33,   34,   33,   29,   29,   61,   34,
       42,   46,   46,   46,   46,   46,   33,   33,   34,   33,
       59,   34,   29,   63,   60,   62,   57,   64,   57,   66,
       29,   66,   33,   33,   34,   33,   67,   33,   33,   34,
       33,   29,   49,   34,   34,   50,   44,   80,   44,   42,

       42,   42,   42,   42,   66,   29,   66,   68,   71,   69,
       29,   72,   42,   70,   34,   73,   33,   33,   34,   33,
       34,   34,   74,   33,   33,   34,   33,   87,   29,   87,
       81,   82,   33,   33,   34,   33,   29,  116,   34,   83,
       29,   34,   85,   77,  201,   84,   79,   78,   33,   33,
       34,   33,   91,   33,   33,   34,   33,   34,   92,   88,
       34,   93,   94,   87,   29,   87,   96,   33,   33,   34,
       33,   33,   33,   34,   33,   89,   90,  218,   95,   33,
       33,   34,   33,   29,  105,   34,   34,  109,  104,  109,
       29,  100,  116,   99,   33,   33,   34,   33,   34,  103,

       29,  106,   33,   33,   34,   33,  101,  116,  117,   34,
      107,   33,   33,   34,   33,   34,  120,  109,  113,  109,
      111,  182,  114,  110,  116,   29,  118,   33,   33,   34,
       33,  119,   33,   33,   34,   33,   29,  112,   33,   33,
       34,  120,  116,   34,  128,   34,  134,  132,  134,  137,
      138,  139,  125,   34,   34,  116,  124,  123,   29,  129,
       33,   33,   34,   33,  130,  130,  131,  130,  134,  116,
      134,   33,   33,   34,   33,  145,   34,  140,  135,   34,
      141,  130,  130,  131,  130,  149,  144,  149,   33,   33,
       34,   33,   29,  116,  116,  151,  152,  143,   34,  148,

      146,  155,  156,   34,  147,  149,   29,  149,  163,  116,
      116,  164,   34,  116,  168,  153,   34,  154,  150,   34,
      170,  169,  170,   34,  216,  157,   33,   33,   34,   33,
      116,  159,  160,  166,  166,  167,  166,  175,  165,   33,
       33,   34,   33,  172,  116,  184,  176,  179,  170,  180,
      170,  166,  166,  167,  166,  177,  177,  178,  177,  186,
      116,  183,  177,  177,  178,  177,  116,   34,  185,  187,
      116,  116,   34,  116,   34,  116,  116,   34,  116,  116,
      116,   34,  116,  189,   34,  116,  116,   34,  188,  192,
      190,  195,  198,  204,  116,   34,  116,   34,  191,  193,

      194,  196,  203,  205,  207,  197,  178,   34,  199,  116,
      200,  212,  202,  174,   34,  213,  178,  167,  206,  208,
      214,  174,  162,  167,  209,  210,   10,   10,   10,   10,
       10,   10,   13,   13,   13,   13,   13,   13,   26,   26,
       26,   26,   26,   26,   28,   28,   28,   28,   28,   28,
       33,   33,   33,   33,   33,   33,   39,  162,  131,   39,
       39,   42,   42,   42,   42,   45,   45,   45,   45,   45,
       48,   48,   48,   48,   48,   48,   56,   56,   58,  127,
      131,   58,   58,   65,   65,   75,   75,   76,  116,  127,
       76,   76,   86,   86,   97,   97,   98,   34,   53,   98,

       98,  108,  108,  115,  115,  115,  115,  115,  115,  121,
      121,  122,   29,   27,  122,  122,  126,  126,  126,  126,
      126,  126,  130,  130,  130,  130,  130,  130,  133,  133,
      136,  136,  136,  136,  136,  136,  142,   37,   32,  142,
      142,  158,   27,  219,  158,  158,  161,  161,  161,  161,
      161,  161,  166,  166,  166,  166,  166,  166,  171,  171,
      171,  171,  171,  171,  173,  173,  173,  173,  173,  173,
      177,  177,  177,  177,  177,  177,  181,  181,  181,  181,
      181,  181,  215,  215,  215,  215,  215,  215,  217,  217,
      217,  217,  217,  217,    9,  219,  219,  219,  219,  219,

      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219
    } ;

static yyconst flex_int16_t yy_chk[730] =
    {   0,
        0,    0,    1,    2,    1,    2,    3,    3,    3,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       12,   15,   17,   31,   17,   18,   18,   18,   23,   30,
       23,   35,   38,   36,   38,   39,  217,   39,   40,   40,

       40,   91,  209,   31,   12,   15,  209,   12,   15,   20,
       20,   20,   20,   36,   41,   44,   41,   44,   30,   47,
       35,   47,   20,   20,   20,   20,   20,   21,   91,   21,
       21,   21,   21,   21,   21,   48,   48,   48,   48,   49,
       49,   49,   49,   21,   22,  215,   22,   22,   22,   22,
       22,   22,   50,   50,   50,   50,   51,   52,   51,   55,
       22,   22,   22,   22,   22,   22,   25,   25,   25,   25,
       49,   54,   69,   54,   50,   52,   57,   55,   57,   58,
       62,   58,   59,   59,   59,   59,   59,   60,   60,   60,
       60,   61,   25,   63,   64,   25,   45,   69,   45,   45,

       45,   45,   45,   45,   66,   70,   66,   60,   62,   61,
       71,   63,   45,   61,   72,   63,   68,   68,   68,   68,
       73,   74,   64,   67,   67,   67,   67,   76,   80,   76,
       70,   71,   77,   77,   77,   77,   82,  198,   83,   72,
       81,   85,   74,   67,  198,   73,   68,   67,   78,   78,
       78,   78,   80,   79,   79,   79,   79,   94,   81,   77,
       84,   82,   83,   87,   93,   87,   85,   88,   88,   88,
       88,   89,   89,   89,   89,   78,   79,  214,   84,   90,
       90,   90,   90,   92,   94,   95,   96,   98,   93,   98,
      102,   89,  175,   88,   99,   99,   99,   99,  105,   92,

      103,   95,  100,  100,  100,  100,   90,  104,  104,  106,
       96,  101,  101,  101,  101,  107,  107,  109,  102,  109,
      100,  175,  103,   99,  128,  125,  105,  110,  110,  110,
      110,  106,  111,  111,  111,  111,  113,  101,  112,  112,
      112,  112,  117,  118,  117,  120,  122,  120,  122,  125,
      128,  128,  113,  129,  132,  138,  111,  110,  137,  118,
      123,  123,  123,  123,  124,  124,  124,  124,  134,  139,
      134,  135,  135,  135,  135,  138,  140,  129,  123,  141,
      132,  136,  136,  136,  136,  142,  137,  142,  143,  143,
      143,  143,  144,  145,  146,  144,  144,  135,  147,  141,

      139,  147,  147,  148,  140,  149,  152,  149,  152,  153,
      154,  153,  156,  164,  156,  145,  179,  146,  143,  157,
      158,  157,  158,  169,  213,  148,  150,  150,  150,  150,
      165,  150,  150,  159,  159,  159,  159,  164,  154,  160,
      160,  160,  160,  160,  176,  179,  165,  169,  170,  170,
      170,  171,  171,  171,  171,  172,  172,  172,  172,  183,
      183,  176,  181,  181,  181,  181,  182,  184,  182,  184,
      185,  186,  187,  188,  190,  189,  191,  193,  194,  195,
      192,  196,  197,  186,  199,  201,  200,  202,  185,  189,
      187,  192,  195,  201,  203,  205,  206,  208,  188,  190,

      191,  193,  200,  202,  204,  194,  177,  210,  196,  211,
      197,  210,  199,  173,  212,  211,  168,  166,  203,  205,
      212,  163,  161,  155,  206,  208,  220,  220,  220,  220,
      220,  220,  221,  221,  221,  221,  221,  221,  222,  222,
      222,  222,  222,  222,  223,  223,  223,  223,  223,  223,
      224,  224,  224,  224,  224,  224,  225,  151,  130,  225,
      225,  226,  226,  226,  226,  227,  227,  227,  227,  227,
      228,  228,  228,  228,  228,  228,  229,  229,  230,  126,
      119,  230,  230,  231,  231,  232,  232,  233,  115,  114,
      233,  233,  234,  234,  235,  235,  236,   33,   32,  236,

      236,  237,  237,  238,  238,  238,  238,  238,  238,  239,
      239,  240,   28,   26,  240,  240,  241,  241,  241,  241,
      241,  241,  242,  242,  242,  242,  242,  242,  243,  243,
      244,  244,  244,  244,  244,  244,  245,   16,   14,  245,
      245,  246,   10,    9,  246,  246,  247,  247,  247,  247,
      247,  247,  248,  248,  248,  248,  248,  248,  249,  249,
      249,  249,  249,  249,  250,  250,  250,  250,  250,  250,
      251,  251,  251,  251,  251,  251,  252,  252,  252,  252,
      252,  252,  253,  253,  253,  253,  253,  253,  254,  254,
      254,  254,  254,  254,  219,  219,  219,  219,  219,  219,

      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[19] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int elf__flex_debug;
int elf__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *elf_text;
#line 1 "elf.l"
/*
// Copyright (c) 2011-2012, Andrew Boktor
// The University of British Columbia
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
// Neither the name of The University of British Columbia nor the names of its
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/*Lex file for elf files output by cuobjdump*/
#line 31 "elf.l"
#include <stdio.h>
#include <string.h>
#include "elf_parser.hh"

#define yylval elf_lval

void elf_error(const char*);



#line 777 "elf_lexer.cc"

#define INITIAL 0
#define cmem 1
#define symtab 2
#define cmem14 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int elf_lex_destroy (void );

int elf_get_debug (void );

void elf_set_debug (int debug_flag  );

YY_EXTRA_TYPE elf_get_extra (void );

void elf_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *elf_get_in (void );

void elf_set_in  (FILE * in_str  );

FILE *elf_get_out (void );

void elf_set_out  (FILE * out_str  );

int elf_get_leng (void );

char *elf_get_text (void );

int elf_get_lineno (void );

void elf_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int elf_wrap (void );
#else
extern int elf_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( elf_text, elf_leng, 1, elf_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( elf_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( elf_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, elf_in))==0 && ferror(elf_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(elf_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int elf_lex (void);

#define YY_DECL int elf_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after elf_text and elf_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 54 "elf.l"


#line 968 "elf_lexer.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! elf_in )
			elf_in = stdin;

		if ( ! elf_out )
			elf_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			elf_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				elf__create_buffer(elf_in,YY_BUF_SIZE );
		}

		elf__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of elf_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 220 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 219 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < elf_leng; ++yyl )
				if ( elf_text[yyl] == '\n' )
					   
    elf_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 56 "elf.l"
{
	BEGIN(cmem);
	yylval.string_value = strdup(elf_text); 
	return C1BEGIN;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 62 "elf.l"
{
	BEGIN(INITIAL);
	yylval.string_value = strdup(elf_text); 
	return LOCALMEM;
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 68 "elf.l"
{
	BEGIN(cmem);
	return C0BEGIN;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 73 "elf.l"
{
	BEGIN(cmem14);
	return C14BEGIN;
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 78 "elf.l"
{
	BEGIN(symtab);
	return STBEGIN;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 83 "elf.l"
{
	//These are the lines before the symtab
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 87 "elf.l"
{
	BEGIN(INITIAL);
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 91 "elf.l"
{
	//printf("Discarding line %s", elf_text);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 95 "elf.l"
{
	//printf("#SPACE#");
	return SPACE2;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "elf.l"
{
	//printf("CMEM VAL: %s \n", elf_text);
	yylval.string_value = strdup(elf_text); 
	return CMEMVAL;
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 106 "elf.l"
{
	return STHEADER;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "elf.l"
{}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 112 "elf.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "elf.l"
{
	yylval.string_value = strdup(elf_text);
	return NUMBER;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 119 "elf.l"
{
	yylval.string_value = strdup(elf_text);
	return IDENTIFIER;
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 124 "elf.l"
{
	BEGIN(INITIAL);
}
	YY_BREAK
/*Reached end of file*/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cmem):
case YY_STATE_EOF(symtab):
case YY_STATE_EOF(cmem14):
#line 128 "elf.l"
return 0;
	YY_BREAK
/*No other rule matched. Throw an error*/
case 17:
YY_RULE_SETUP
#line 131 "elf.l"
elf_error("Invalid token");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 133 "elf.l"
ECHO;
	YY_BREAK
#line 1208 "elf_lexer.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed elf_in at a new source and called
			 * elf_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = elf_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( elf_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * elf_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of elf_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					elf_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			elf_restart(elf_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) elf_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 220 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 220 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 219);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					elf_restart(elf_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( elf_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve elf_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    elf_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void elf_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        elf_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            elf__create_buffer(elf_in,YY_BUF_SIZE );
	}

	elf__init_buffer(YY_CURRENT_BUFFER,input_file );
	elf__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void elf__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		elf_pop_buffer_state();
	 *		elf_push_buffer_state(new_buffer);
     */
	elf_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	elf__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (elf_wrap()) processing, but the only time this flag
	 * is looked at is after elf_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void elf__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	elf_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE elf__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) elf_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in elf__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) elf_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in elf__create_buffer()" );

	b->yy_is_our_buffer = 1;

	elf__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with elf__create_buffer()
 * 
 */
    void elf__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		elf_free((void *) b->yy_ch_buf  );

	elf_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a elf_restart() or at EOF.
 */
    static void elf__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	elf__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then elf__init_buffer was _probably_
     * called from elf_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void elf__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		elf__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void elf_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	elf_ensure_buffer_stack();

	/* This block is copied from elf__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from elf__switch_to_buffer. */
	elf__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void elf_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	elf__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		elf__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void elf_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)elf_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in elf_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)elf_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in elf_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE elf__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) elf_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in elf__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	elf__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to elf_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       elf__scan_bytes() instead.
 */
YY_BUFFER_STATE elf__scan_string (yyconst char * yystr )
{
    
	return elf__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to elf_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE elf__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) elf_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in elf__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = elf__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in elf__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up elf_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		elf_text[elf_leng] = (yy_hold_char); \
		(yy_c_buf_p) = elf_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		elf_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int elf_get_lineno  (void)
{
        
    return elf_lineno;
}

/** Get the input stream.
 * 
 */
FILE *elf_get_in  (void)
{
        return elf_in;
}

/** Get the output stream.
 * 
 */
FILE *elf_get_out  (void)
{
        return elf_out;
}

/** Get the length of the current token.
 * 
 */
int elf_get_leng  (void)
{
        return elf_leng;
}

/** Get the current token.
 * 
 */

char *elf_get_text  (void)
{
        return elf_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void elf_set_lineno (int  line_number )
{
    
    elf_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see elf__switch_to_buffer
 */
void elf_set_in (FILE *  in_str )
{
        elf_in = in_str ;
}

void elf_set_out (FILE *  out_str )
{
        elf_out = out_str ;
}

int elf_get_debug  (void)
{
        return elf__flex_debug;
}

void elf_set_debug (int  bdebug )
{
        elf__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from elf_lex_destroy(), so don't allocate here.
     */

    /* We do not touch elf_lineno unless the option is enabled. */
    elf_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    elf_in = stdin;
    elf_out = stdout;
#else
    elf_in = (FILE *) 0;
    elf_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * elf_lex_init()
     */
    return 0;
}

/* elf_lex_destroy is for both reentrant and non-reentrant scanners. */
int elf_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		elf__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		elf_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	elf_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * elf_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *elf_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *elf_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void elf_free (void * ptr )
{
	free( (char *) ptr );	/* see elf_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "elf.l"


void elf_error(const char* message)
{
	printf("   ");
	printf("%s",message);
	printf(" near \"");
	printf("%s",elf_text);
	printf("\"");
	printf(" on line "); 
	char line[5];
	sprintf(line, "%i", elf_lineno);
	printf("%s",line);
	printf("\n");
	abort();
}

