#line 2 "cuobjdump_lexer.c"

#line 4 "cuobjdump_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cuobjdump__create_buffer
#define yy_delete_buffer cuobjdump__delete_buffer
#define yy_flex_debug cuobjdump__flex_debug
#define yy_init_buffer cuobjdump__init_buffer
#define yy_flush_buffer cuobjdump__flush_buffer
#define yy_load_buffer_state cuobjdump__load_buffer_state
#define yy_switch_to_buffer cuobjdump__switch_to_buffer
#define yyin cuobjdump_in
#define yyleng cuobjdump_leng
#define yylex cuobjdump_lex
#define yylineno cuobjdump_lineno
#define yyout cuobjdump_out
#define yyrestart cuobjdump_restart
#define yytext cuobjdump_text
#define yywrap cuobjdump_wrap
#define yyalloc cuobjdump_alloc
#define yyrealloc cuobjdump_realloc
#define yyfree cuobjdump_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cuobjdump_restart(cuobjdump_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cuobjdump_leng;

extern FILE *cuobjdump_in, *cuobjdump_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cuobjdump_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cuobjdump_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < cuobjdump_leng; ++yyl )\
                    if ( cuobjdump_text[yyl] == '\n' )\
                        --cuobjdump_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cuobjdump_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cuobjdump_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cuobjdump_restart()), so that the user can continue scanning by
	 * just pointing cuobjdump_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cuobjdump_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cuobjdump_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cuobjdump_wrap()'s to do buffer switches
 * instead of setting up a fresh cuobjdump_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cuobjdump_restart (FILE *input_file  );
void cuobjdump__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cuobjdump__create_buffer (FILE *file,int size  );
void cuobjdump__delete_buffer (YY_BUFFER_STATE b  );
void cuobjdump__flush_buffer (YY_BUFFER_STATE b  );
void cuobjdump_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void cuobjdump_pop_buffer_state (void );

static void cuobjdump_ensure_buffer_stack (void );
static void cuobjdump__load_buffer_state (void );
static void cuobjdump__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cuobjdump__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cuobjdump__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cuobjdump__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cuobjdump__scan_bytes (yyconst char *bytes,int len  );

void *cuobjdump_alloc (yy_size_t  );
void *cuobjdump_realloc (void *,yy_size_t  );
void cuobjdump_free (void *  );

#define yy_new_buffer cuobjdump__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cuobjdump_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cuobjdump__create_buffer(cuobjdump_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cuobjdump_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cuobjdump__create_buffer(cuobjdump_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cuobjdump_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cuobjdump_in = (FILE *) 0, *cuobjdump_out = (FILE *) 0;

typedef int yy_state_type;

extern int cuobjdump_lineno;

int cuobjdump_lineno = 1;

extern char *cuobjdump_text;
#define yytext_ptr cuobjdump_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cuobjdump_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cuobjdump_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[383] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   23,   21,   20,    2,   21,   21,   21,    5,
        2,   21,   21,   21,    8,    2,   21,   21,   21,   21,
        7,    2,   21,   21,   21,    9,    2,   21,    9,   21,
        9,    9,    9,    9,    9,   19,    2,   19,   19,    2,
        0,    0,    0,    5,    2,    0,    0,    0,    8,    2,
        0,    0,    0,    7,    0,    0,    2,    0,    0,    0,
        9,    2,    0,    9,    0,    9,    9,    9,    9,    9,
        9,    9,   19,    2,   19,   19,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    9,    9,

        9,    9,    9,    9,    9,    9,   19,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,
        9,    9,    9,    0,    9,    9,    9,    9,   19,   19,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,   13,    0,    0,    9,    0,    0,    9,    9,    9,
       19,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    0,    0,    9,    0,    0,    9,    9,
        9,   19,   19,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   11,    0,    9,    0,   15,    9,    9,
        9,   19,   19,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,
        9,    9,    9,   19,   19,   19,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    9,    0,    9,    0,    9,   19,   19,   19,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    9,    0,    9,   19,
       19,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    9,    0,    0,
       14,    9,   19,   19,   19,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        9,    0,    0,    9,   19,   19,   19,    0,    0,    0,
        1,    0,    0,    0,    1,    0,    0,    0,    1,    0,
        0,    0,    0,    1,    0,    0,    0,    0,   17,    9,
       19,   19,   19,    0,    0,    0,    0,    0,    0,    0,
        0,    6,    0,    0,    0,    0,   19,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   12,   16,   18,
       19,   19,    0,    0,    0,    0,    0,    0,    0,    0,
       10,   19,   19,    4,    3,    4,    3,    4,    3,    4,
        3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    1,    1,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    1,    1,
        9,    1,    1,    1,   10,   10,   10,   10,   10,   11,
       10,   10,   10,   10,   10,   10,   10,   10,   12,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       13,    1,   14,    1,   15,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   10,   10,   25,   26,   27,
       28,   29,   10,   30,   31,   32,   33,   34,   10,   35,
       10,   36,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[37] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    1,    1,    3,
        3,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[399] =
    {   0,
        0,    1,    2,    3,   12,   13,   41,   69,   98,    0,
       46,   53,  632,  633,  633,   11,  615,  598,  626,  633,
       19,   18,   30,  625,  633,   32,   24,   33,  624,   65,
      633,   44,   58,   51,   34,    0,   71,  617,  609,   78,
      594,  595,   30,  603,   56,    0,   83,  605,  588,   85,
      587,  583,  614,  633,   90,  132,   60,  613,  633,  133,
      134,  135,  612,  633,  139,  141,  142,  143,  144,  147,
        0,  145,  605,  581,  607,  593,  134,  579,  578,  588,
      579,  571,    0,  148,  573,  569,  586,  586,  155,   78,
      156,  158,  159,  164,  162,  592,  583,  173,  576,  578,

      568,  592,  563,  567,  574,  576,  574,  574,  565,  557,
      153,  165,  168,  178,  180,  182,  184,  578,  562,  571,
      580,  579,  558,  562,  576,  547,  545,  546,  552,  544,
      547,  561,  185,  186,  187,  188,  190,  192,  191,  563,
      544,  633,  561,  535,  543,  547,  557,  541,  546,  551,
      535,  549,  556,  530,  198,  194,  202,  196,  204,  207,
      208,  549,  553,  552,  535,  534,  536,  548,  530,  530,
      520,  544,  518,  198,  514,  213,  216,  218,  217,  221,
       25,  219,  536,  633,  514,  528,  509,  633,  517,  510,
      507,  210,  506,  512,  504,  511,  228,  223,  233,  229,

      226,  237,  231,  240,  241,  243,  525,  502,  501,  509,
      510,  525,  504,  502,  494,  501,  503,  488,  494,  249,
      225,  256,  259,  260,  261,  262,  263,  265,  266,  512,
      496,  495,  514,  487,  507,  487,  493,  478,  484,  507,
      506,  482,  270,  272,  274,  275,  278,  282,  283,  287,
      285,  289,  499,  479,  470,  481,  500,  499,  475,  497,
      496,  472,  480,  479,  465,  290,  294,  268,  297,  299,
      300,  301,  302,  303,  304,  486,  467,  473,  465,  482,
      633,  459,  471,  470,  456,  458,  457,  481,  310,  311,
      480,  318,  319,  479,  320,  321,  322,  478,  471,  475,

      474,  456,  472,  349,  447,  446,  470,  453,  452,  467,
      633,  307,  324,  466,  633,  337,  341,  465,  633,  342,
      352,  327,  464,  633,  457,  456,  455,  435,  633,  371,
      443,  442,  457,  439,  438,  339,  361,  362,  363,  366,
      367,  633,  448,  452,  451,  451,  433,  432,  443,  442,
      329,  333,  385,  386,  387,  388,  440,  633,  633,  633,
      440,  439,  443,  442,  441,  440,  439,  419,  389,  375,
      633,  374,  365,  633,  633,  633,  633,  633,  633,  633,
      633,  633,  396,  399,  402,  405,  408,  411,  414,  417,
      364,  420,  423,  426,  429,  432,  435,  438

    } ;

static yyconst flex_int16_t yy_def[399] =
    {   0,
      383,  383,  384,  384,  385,  385,  386,  386,  382,    9,
      387,  387,  382,  382,  382,  382,  382,  382,  388,  382,
      388,  388,  388,  389,  382,  389,  389,  389,  390,  390,
      382,  390,  390,  390,  390,  391,  391,  382,  391,  382,
      391,  391,  391,  391,  391,  392,  392,  392,  392,  382,
      382,  382,  388,  382,  388,  388,  388,  389,  382,  389,
      389,  389,  390,  382,  390,  390,  390,  390,  390,  390,
      391,  391,  382,  391,  382,  391,  391,  391,  391,  391,
      391,  391,  392,  392,  392,  392,  382,  382,  388,  388,
      389,  389,  390,  390,  390,  382,  391,  382,  391,  391,

      391,  391,  391,  391,  391,  391,  392,  392,  382,  382,
      388,  388,  389,  389,  390,  390,  390,  382,  391,  382,
      391,  391,  391,  382,  391,  391,  391,  391,  392,  392,
      382,  382,  388,  388,  389,  389,  390,  390,  390,  382,
      391,  382,  382,  382,  391,  382,  382,  391,  391,  391,
      392,  392,  382,  382,  388,  388,  389,  389,  390,  390,
      390,  382,  391,  382,  382,  391,  382,  382,  391,  391,
      391,  392,  392,  382,  382,  388,  388,  389,  389,  390,
      390,  390,  382,  382,  382,  391,  382,  382,  391,  391,
      391,  392,  392,  382,  382,  382,  388,  388,  388,  389,

      389,  389,  390,  390,  390,  390,  382,  382,  391,  382,
      391,  391,  391,  392,  392,  392,  382,  382,  382,  388,
      388,  388,  389,  389,  389,  390,  390,  390,  390,  382,
      382,  391,  382,  391,  382,  391,  392,  392,  392,  382,
      382,  382,  388,  388,  388,  389,  389,  389,  390,  390,
      390,  390,  382,  382,  391,  382,  391,  382,  391,  392,
      392,  392,  382,  382,  382,  388,  388,  388,  389,  389,
      389,  390,  390,  390,  390,  382,  382,  391,  382,  382,
      382,  391,  392,  392,  392,  382,  382,  393,  388,  388,
      394,  389,  389,  395,  390,  390,  390,  396,  382,  382,

      391,  382,  382,  397,  392,  392,  398,  382,  382,  393,
      382,  388,  388,  394,  382,  389,  389,  395,  382,  390,
      390,  390,  396,  382,  382,  382,  382,  382,  382,  397,
      392,  392,  398,  382,  382,  388,  388,  389,  389,  390,
      390,  382,  382,  382,  382,  382,  392,  392,  382,  382,
      388,  388,  389,  389,  390,  390,  382,  382,  382,  382,
      392,  392,  382,  382,  388,  388,  389,  389,  390,  390,
      382,  392,  392,  382,  382,  382,  382,  382,  382,  382,
      382,    0,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382

    } ;

static yyconst flex_int16_t yy_nxt[670] =
    {   0,
      382,  382,   15,   15,   20,   20,   16,   16,   21,   21,
       17,   17,   22,   22,   25,   25,   50,   50,   26,   26,
       54,   54,   27,   27,   55,   55,   59,   64,   18,   18,
       23,   23,   54,   56,   59,   59,   64,   60,   60,   61,
       28,   28,   30,   31,   30,   78,   64,   32,   15,   67,
       67,   33,   47,   64,  205,   15,   48,   79,   34,   47,
       64,   57,   54,   48,   62,   70,   65,   64,   65,   35,
       30,   31,   30,   68,   49,   32,   72,   72,   69,   33,
       54,   49,   66,   75,   75,   81,   34,   82,   84,   84,
       50,   50,   54,  112,   90,   55,   55,   35,   14,   14,

       15,   14,   14,   36,   37,   14,   38,   36,   39,   36,
       40,   14,   36,   41,   36,   42,   36,   36,   36,   36,
       43,   44,   36,   36,   36,   36,   45,   36,   36,   36,
       36,   36,   36,   36,   54,   59,   59,   59,   60,   60,
       65,   64,   65,   64,   64,   64,   64,   67,   67,   64,
       72,   72,  100,   84,   84,   54,   66,   54,   59,  101,
       59,   64,   94,   89,   64,   91,   64,   54,   69,   92,
       59,  111,  113,  114,   93,  115,  133,  117,  120,  120,
       59,   95,   64,  116,   64,  138,   64,   54,   54,   59,
       59,  135,   64,   64,   64,  134,   54,  156,   59,  158,

       54,  176,  161,  137,   59,  178,   64,  180,  136,   64,
       64,  155,  160,  157,  139,   54,  159,  194,   54,   59,
       59,   64,  177,   64,  179,   54,  195,   54,   59,  214,
       54,   59,  197,   64,  181,   54,  182,  200,  215,   59,
      203,  198,   64,   64,  228,   64,  201,  199,  202,  204,
      206,   54,  220,  223,  221,  226,  222,  224,   54,  244,
      225,   59,   59,   59,   64,   64,  229,   64,   64,  243,
       54,  227,   54,  266,   54,  267,   54,   59,  269,  246,
       59,  270,  249,  245,   59,   64,  272,   64,  248,   64,
      273,   64,   54,  252,  247,  251,   54,  250,  291,   59,

      268,   59,   59,   64,   64,   64,   64,  289,  271,   54,
      274,  290,   54,   54,  292,  275,  293,  297,  295,  296,
       59,   59,   64,   64,   64,  336,   54,  322,  322,  342,
      294,   54,  322,  322,  298,   54,  365,  312,  313,   59,
      366,   54,  337,   59,   64,  316,  317,  320,  321,  310,
      310,  311,  310,  310,   64,  338,  310,  310,  351,  339,
      340,  310,  310,   54,   59,   59,   71,  375,   64,   64,
      341,  310,  310,  311,  310,  310,  374,  381,  310,  310,
      352,  353,  354,  310,  310,  355,  356,   59,   59,   64,
       64,  380,  367,  368,  369,  370,   14,   14,   14,   19,

       19,   19,   24,   24,   24,   29,   29,   29,   46,   46,
       46,   53,   53,   53,   58,   58,   58,   63,   63,   63,
       83,  379,   83,  310,  310,  310,  314,  314,  314,  318,
      318,  318,  323,  323,  323,  330,  330,  330,  333,  333,
      333,  378,  377,  376,  375,  374,  373,  372,  371,  364,
      363,  362,  361,  360,  359,  358,  357,  350,  349,  311,
      348,  347,  346,  345,  344,  343,  324,  319,  315,  311,
      335,  334,  311,  332,  331,  329,  328,  327,  326,  325,
      324,  319,  315,  311,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  288,  287,  286,  285,  284,

      283,  282,  281,  280,  279,  278,  277,  276,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  219,  218,  217,  216,  213,  212,
      211,  210,  209,  208,  207,  196,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  174,  183,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  119,

      118,  110,  109,  108,  107,  106,  105,  104,  103,  102,
       99,   98,   97,   96,   64,   59,   54,   88,   87,   86,
       85,   80,   77,   76,   74,   73,   64,   59,   54,   52,
       51,  382,   13,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

static yyconst flex_int16_t yy_chk[670] =
    {   0,
        0,    0,    1,    2,    3,    4,    1,    2,    3,    4,
        1,    2,    3,    4,    5,    6,   16,   16,    5,    6,
       22,   21,    5,    6,   21,   21,   27,  181,    1,    2,
        3,    4,   23,   22,   26,   28,   35,   26,   26,   27,
        5,    6,    7,    7,    7,   43,   32,    7,   11,   32,
       32,    7,   11,   34,  181,   12,   11,   43,    7,   12,
       33,   23,   57,   12,   28,   35,   30,   30,   30,    7,
        8,    8,    8,   33,   11,    8,   37,   37,   34,    8,
       90,   12,   30,   40,   40,   45,    8,   45,   47,   47,
       50,   50,   55,   90,   57,   55,   55,    8,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   56,   60,   61,   62,   60,   60,
       65,   65,   65,   66,   67,   68,   69,   67,   67,   70,
       72,   72,   77,   84,   84,  111,   65,   89,   91,   77,
       92,   93,   69,   56,   95,   61,   94,  112,   66,   62,
      113,   89,   91,   92,   68,   93,  111,   95,   98,   98,
      114,   70,  115,   94,  116,  116,  117,  133,  134,  135,
      136,  113,  137,  139,  138,  112,  156,  134,  158,  136,

      155,  155,  139,  115,  157,  157,  159,  159,  114,  160,
      161,  133,  138,  135,  117,  176,  137,  174,  177,  179,
      178,  182,  156,  180,  158,  198,  174,  221,  201,  192,
      197,  200,  176,  203,  160,  199,  161,  178,  192,  202,
      180,  176,  204,  205,  205,  206,  178,  177,  179,  180,
      182,  220,  197,  200,  198,  203,  199,  201,  222,  221,
      202,  223,  224,  225,  226,  227,  206,  228,  229,  220,
      268,  204,  243,  243,  244,  244,  245,  246,  246,  223,
      247,  247,  226,  222,  248,  249,  249,  251,  225,  250,
      250,  252,  266,  229,  224,  228,  267,  227,  268,  269,

      245,  270,  271,  272,  273,  274,  275,  266,  248,  312,
      251,  267,  289,  290,  269,  252,  270,  274,  272,  273,
      292,  293,  295,  296,  297,  312,  313,  297,  297,  322,
      271,  351,  322,  322,  275,  352,  351,  289,  290,  316,
      352,  336,  313,  317,  320,  292,  293,  295,  296,  304,
      304,  304,  304,  304,  321,  316,  304,  304,  336,  317,
      320,  304,  304,  337,  338,  339,  391,  373,  340,  341,
      321,  330,  330,  330,  330,  330,  372,  370,  330,  330,
      337,  338,  339,  330,  330,  340,  341,  353,  354,  355,
      356,  369,  353,  354,  355,  356,  383,  383,  383,  384,

      384,  384,  385,  385,  385,  386,  386,  386,  387,  387,
      387,  388,  388,  388,  389,  389,  389,  390,  390,  390,
      392,  368,  392,  393,  393,  393,  394,  394,  394,  395,
      395,  395,  396,  396,  396,  397,  397,  397,  398,  398,
      398,  367,  366,  365,  364,  363,  362,  361,  357,  350,
      349,  348,  347,  346,  345,  344,  343,  335,  334,  333,
      332,  331,  328,  327,  326,  325,  323,  318,  314,  310,
      309,  308,  307,  306,  305,  303,  302,  301,  300,  299,
      298,  294,  291,  288,  287,  286,  285,  284,  283,  282,
      280,  279,  278,  277,  276,  265,  264,  263,  262,  261,

      260,  259,  258,  257,  256,  255,  254,  253,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  196,  195,  194,  193,  191,  190,
      189,  187,  186,  185,  183,  175,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      141,  140,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   97,

       96,   88,   87,   86,   85,   82,   81,   80,   79,   78,
       76,   75,   74,   73,   63,   58,   53,   52,   51,   49,
       48,   44,   42,   41,   39,   38,   29,   24,   19,   18,
       17,   13,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[23] =
    {   0,
1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cuobjdump__flex_debug;
int cuobjdump__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cuobjdump_text;
#line 1 "cuobjdump.l"
/*
// Copyright (c) 2011-2012, Andrew Boktor
// The University of British Columbia
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
// Neither the name of The University of British Columbia nor the names of its
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/*Lex file for output of cuobjdump*/
#line 31 "cuobjdump.l"
#include <stdio.h>
#include <string.h>
#include "cuobjdump_parser.h"

#define YY_NEVER_INTERACTIVE 1
#define YY_NO_INPUT
#define YY_NO_TOP_STATE

#define YYDEBUG 1

#define yylval cuobjdump_lval

void cuobjdump_error(const char*);





#line 822 "cuobjdump_lexer.c"

#define INITIAL 0
#define ptxcode 1
#define sasscode 2
#define elfcode 3
#define header 4
#define endheader 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cuobjdump_lex_destroy (void );

int cuobjdump_get_debug (void );

void cuobjdump_set_debug (int debug_flag  );

YY_EXTRA_TYPE cuobjdump_get_extra (void );

void cuobjdump_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *cuobjdump_get_in (void );

void cuobjdump_set_in  (FILE * in_str  );

FILE *cuobjdump_get_out (void );

void cuobjdump_set_out  (FILE * out_str  );

int cuobjdump_get_leng (void );

char *cuobjdump_get_text (void );

int cuobjdump_get_lineno (void );

void cuobjdump_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cuobjdump_wrap (void );
#else
extern int cuobjdump_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cuobjdump_text, cuobjdump_leng, 1, cuobjdump_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cuobjdump_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cuobjdump_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cuobjdump_in))==0 && ferror(cuobjdump_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cuobjdump_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cuobjdump_lex (void);

#define YY_DECL int cuobjdump_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cuobjdump_text and cuobjdump_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 64 "cuobjdump.l"



#line 1026 "cuobjdump_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cuobjdump_in )
			cuobjdump_in = stdin;

		if ( ! cuobjdump_out )
			cuobjdump_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cuobjdump_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cuobjdump__create_buffer(cuobjdump_in,YY_BUF_SIZE );
		}

		cuobjdump__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cuobjdump_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 383 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 382 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < cuobjdump_leng; ++yyl )
				if ( cuobjdump_text[yyl] == '\n' )
					   
    cuobjdump_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 67 "cuobjdump.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); return DECIMAL;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 71 "cuobjdump.l"
{
	yy_push_state(ptxcode);
	yy_push_state(header);
	yylval.string_value = strdup(cuobjdump_text);
	return PTXHEADER;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 77 "cuobjdump.l"
{
	yy_push_state(elfcode);
	yy_push_state(header);
	yylval.string_value = strdup(cuobjdump_text);
	return ELFHEADER;
}
	YY_BREAK
/*PTX code tokens*/
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 84 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); return PTXLINE;
	YY_BREAK
/*ELF code tokens*/
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 87 "cuobjdump.l"
{
	BEGIN(sasscode); 
	yylval.string_value = strdup(cuobjdump_text); 
	return SASSLINE;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 92 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); return ELFLINE;
	YY_BREAK
/*SASS code tokens*/
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 95 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); return SASSLINE;
	YY_BREAK
/*Header tokens*/
case 9:
YY_RULE_SETUP
#line 98 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); return IDENTIFIER;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "cuobjdump.l"
return H_SEPARATOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "cuobjdump.l"
return H_ARCH;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "cuobjdump.l"
return H_CODEVERSION;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "cuobjdump.l"
return CODEVERSION;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "cuobjdump.l"
return H_PRODUCER;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "cuobjdump.l"
return H_HOST;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "cuobjdump.l"
return H_COMPILESIZE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "cuobjdump.l"
BEGIN(endheader); return H_IDENTIFIER;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 107 "cuobjdump.l"

	YY_BREAK
/* Looking for the identifier (filename) then the header is done */
/* <endheader>[[:alnum:]_\./]+	yylval.string_value = strdup(cuobjdump_text); yy_pop_state(); return FILENAME; */
case 19:
YY_RULE_SETUP
#line 111 "cuobjdump.l"
yylval.string_value = strdup(cuobjdump_text); yy_pop_state(); return FILENAME;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 114 "cuobjdump.l"
return NEWLINE;
	YY_BREAK
/*Reached end of file*/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ptxcode):
case YY_STATE_EOF(sasscode):
case YY_STATE_EOF(elfcode):
case YY_STATE_EOF(header):
case YY_STATE_EOF(endheader):
#line 117 "cuobjdump.l"
BEGIN(INITIAL);return 0;
	YY_BREAK
/*No other rule matched. Throw an error*/
case 21:
YY_RULE_SETUP
#line 120 "cuobjdump.l"
cuobjdump_error("Invalid token");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "cuobjdump.l"
ECHO;
	YY_BREAK
#line 1265 "cuobjdump_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cuobjdump_in at a new source and called
			 * cuobjdump_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cuobjdump_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cuobjdump_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cuobjdump_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cuobjdump_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cuobjdump_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cuobjdump_restart(cuobjdump_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cuobjdump_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 383 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 383 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 382);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cuobjdump_restart(cuobjdump_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cuobjdump_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cuobjdump_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    cuobjdump_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cuobjdump_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cuobjdump_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cuobjdump__create_buffer(cuobjdump_in,YY_BUF_SIZE );
	}

	cuobjdump__init_buffer(YY_CURRENT_BUFFER,input_file );
	cuobjdump__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cuobjdump__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cuobjdump_pop_buffer_state();
	 *		cuobjdump_push_buffer_state(new_buffer);
     */
	cuobjdump_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cuobjdump__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cuobjdump_wrap()) processing, but the only time this flag
	 * is looked at is after cuobjdump_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cuobjdump__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cuobjdump_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cuobjdump__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cuobjdump_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cuobjdump__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cuobjdump_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cuobjdump__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cuobjdump__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cuobjdump__create_buffer()
 * 
 */
    void cuobjdump__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cuobjdump_free((void *) b->yy_ch_buf  );

	cuobjdump_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cuobjdump_restart() or at EOF.
 */
    static void cuobjdump__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cuobjdump__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cuobjdump__init_buffer was _probably_
     * called from cuobjdump_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cuobjdump__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cuobjdump__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cuobjdump_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cuobjdump_ensure_buffer_stack();

	/* This block is copied from cuobjdump__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cuobjdump__switch_to_buffer. */
	cuobjdump__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cuobjdump_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cuobjdump__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cuobjdump__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cuobjdump_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cuobjdump_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cuobjdump_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cuobjdump_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cuobjdump_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cuobjdump__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cuobjdump_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cuobjdump__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cuobjdump__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cuobjdump_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cuobjdump__scan_bytes() instead.
 */
YY_BUFFER_STATE cuobjdump__scan_string (yyconst char * yystr )
{
    
	return cuobjdump__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cuobjdump_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cuobjdump__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cuobjdump_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cuobjdump__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cuobjdump__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cuobjdump__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) cuobjdump_alloc(new_size  );

		else
			(yy_start_stack) = (int *) cuobjdump_realloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cuobjdump_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cuobjdump_text[cuobjdump_leng] = (yy_hold_char); \
		(yy_c_buf_p) = cuobjdump_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cuobjdump_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cuobjdump_get_lineno  (void)
{
        
    return cuobjdump_lineno;
}

/** Get the input stream.
 * 
 */
FILE *cuobjdump_get_in  (void)
{
        return cuobjdump_in;
}

/** Get the output stream.
 * 
 */
FILE *cuobjdump_get_out  (void)
{
        return cuobjdump_out;
}

/** Get the length of the current token.
 * 
 */
int cuobjdump_get_leng  (void)
{
        return cuobjdump_leng;
}

/** Get the current token.
 * 
 */

char *cuobjdump_get_text  (void)
{
        return cuobjdump_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cuobjdump_set_lineno (int  line_number )
{
    
    cuobjdump_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cuobjdump__switch_to_buffer
 */
void cuobjdump_set_in (FILE *  in_str )
{
        cuobjdump_in = in_str ;
}

void cuobjdump_set_out (FILE *  out_str )
{
        cuobjdump_out = out_str ;
}

int cuobjdump_get_debug  (void)
{
        return cuobjdump__flex_debug;
}

void cuobjdump_set_debug (int  bdebug )
{
        cuobjdump__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cuobjdump_lex_destroy(), so don't allocate here.
     */

    /* We do not touch cuobjdump_lineno unless the option is enabled. */
    cuobjdump_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    cuobjdump_in = stdin;
    cuobjdump_out = stdout;
#else
    cuobjdump_in = (FILE *) 0;
    cuobjdump_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cuobjdump_lex_init()
     */
    return 0;
}

/* cuobjdump_lex_destroy is for both reentrant and non-reentrant scanners. */
int cuobjdump_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cuobjdump__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cuobjdump_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	cuobjdump_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        cuobjdump_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cuobjdump_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cuobjdump_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cuobjdump_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cuobjdump_free (void * ptr )
{
	free( (char *) ptr );	/* see cuobjdump_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "cuobjdump.l"


void cuobjdump_error(const char* message)
{
	printf("   "); printf(message); printf(" near \""); printf(cuobjdump_text); printf("\"");
	printf(" on line "); 
	char line[5]; sprintf(line, "%i", cuobjdump_lineno); printf(line);
	printf("\n");
}

